Controllers/DialogController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Site_Lab12.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site_Lab12.Controllers
{
    [Authorize]
    public class DialogController : Controller
    {
        public static ApplicationDbContext dbContext = new ApplicationDbContext();
        ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(dbContext));
   //     PostContext postContext = new PostContext();
      //  ChatHub chat = new ChatHub();
        MessageContext messageContext = new MessageContext();
        // GET: Dialog
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Dialog(string userId)
        {
            string currentUserId = User.Identity.GetUserId();
            var ser = userManager.Users.Where(m => m.Id == userId).FirstOrDefault();
            if (userId != null)
            {
                var currentChat = messageContext.Chats.Where(m => (m.UserFirstId == userId && m.UserSecondId == currentUserId) || (m.UserFirstId == currentUserId && m.UserSecondId == userId)).FirstOrDefault();
                if (currentChat == null)
                {
                    Models.Chat chat = new Models.Chat { UserFirstId = currentUserId, UserSecondId = userId };
                    currentChat = chat;
                    messageContext.Chats.Add(currentChat);
                    messageContext.SaveChanges();
                    dbContext.SaveChanges();
                }
                currentChat = messageContext.Chats.Where(m => (m.UserFirstId == userId && m.UserSecondId == currentUserId) || (m.UserFirstId == currentUserId && m.UserSecondId == userId)).FirstOrDefault();
                var messages = messageContext.Messages.Where(m => (m.UserSenderId == currentUserId && m.UserToSendId == userId)||(m.UserToSendId == currentUserId && m.UserSenderId == userId)).ToList();
                ViewData["senderId"] = currentUserId;
                ViewData["recipientId"] = userId;
                ViewData["recipientName"] = ser.UserName;

                return View(messages);
                }
               
                
            
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Site_Lab12.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Site_Lab12.Controllers
{
    public class HomeController : Controller
    {
        public static ApplicationDbContext dbContext = new ApplicationDbContext();
        ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(dbContext));
        public PostContext postContext = new PostContext();
        public ActionResult Index()
        {
            var allUsers = userManager.Users.ToList();
            ViewBag.posts = postContext.Posts.ToList();
          
            return View(allUsers);
        }

        [Authorize]
        public ActionResult HomePage()
        {
            string name = User.Identity.GetUserId();
            //   var ser = dbContext.ApplicationsUsers.Where(m => m.Email == name);
            var ser2 = userManager.Users.Where(m => m.Id == name).FirstOrDefault();
            if (ser2!=null)
            {
                return View(ser2);

            }
            return View(ser2);
        }

        [Authorize]
        public ActionResult UsersList()
        {
            var users = userManager.Users.ToList();
            return View(users);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit()
        {
            string name = User.Identity.GetUserId();
            //   var ser = dbContext.ApplicationsUsers.Where(m => m.Email == name);
            var ser2 = userManager.Users.Where(m => m.Id == name).FirstOrDefault();
            if (ser2 != null)
            {
                return View(ser2);

            }
            return View(ser2);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(ApplicationUser user)
        {
            string name = User.Identity.GetUserId();
            var ser = userManager.Users.Where(m => m.Id == name).FirstOrDefault();
            ser.Email = user.Email;
            ser.UserName = user.UserName;
            ser.PhoneNumber = user.PhoneNumber;
            userManager.UpdateAsync(ser);
            dbContext.SaveChanges();

            return RedirectToAction("HomePage");
        }
        public async System.Threading.Tasks.Task<ActionResult> Edit2Async(string Id)
        {
            if (Id!=null)
            {
                if (Id==User.Identity.GetUserId())
                {
                    var ser = await userManager.FindByIdAsync(Id);
                    if (ser != null)
                    {
                        return View(ser);
                    }
                    else
                    {

                        return RedirectToAction("HomePage");
                    }

                }
                else if(User.IsInRole("admin"))
                {
                   var ser = await userManager.FindByIdAsync(Id);
                    if (ser != null)
                    {
                        return View(ser);
                    }
                    else
                    {

                        return RedirectToAction("HomePage");
                    }
                }

            }
            return RedirectToAction("HomePage");


        }
        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> Edit2Async(ApplicationUser user)
        {
            var ser = await userManager.FindByIdAsync(User.Identity.GetUserId());
            if (ser!=null)
            {
                ser.Email = user.Email;
                ser.UserName = user.UserName;
                ser.PhoneNumber = user.PhoneNumber;
                IdentityResult res = await userManager.UpdateAsync(ser);
                if (res.Succeeded)
                {
                    return View("HomePage",ser);
                }
            }
            return RedirectToAction("Index");
        }

        public async System.Threading.Tasks.Task<ActionResult> Details(string Id)

        {
            if (Id!=null)
            {
                var posts = postContext.Posts.Where(m => m.AuthorId == Id).ToList();
                ViewData["Posts"] = posts;
                var ser = await userManager.FindByIdAsync(Id);
                if (ser != null)
                {
                    return View(ser);
                }
                else
                {

                    return RedirectToAction("HomePage");
                }

            }
            return RedirectToAction("HomePage");
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult LatestPosts()
        {
            var allPosts = postContext.Posts.ToList();
       
            return PartialView(allPosts);
        }
    }
}

Controllers/PostController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Site_Lab12.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site_Lab12.Controllers
{
    [Authorize]

    public class PostController : Controller
    {

        public static ApplicationDbContext dbContext = new ApplicationDbContext();
        ApplicationUserManager userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(dbContext));
        PostContext postContext = new PostContext();
        // GET: Post
        [Authorize]
        public ActionResult My()
        {
            //Post p1 = new Post { BodyText = "Lorem ipsum", AuthorId = User.Identity.GetUserId(), Title = "MyPost", Date = DateTime.Now };
            //postContext.Posts.Add(p1);
            //postContext.SaveChanges();
            var allPost = postContext.Posts.ToList();
            string Id = User.Identity.GetUserId();
            var posts = postContext.Posts.Where(m => m.AuthorId == Id).ToList();
            
            return View(posts);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UserPosts(string id)
        {
            var posts = postContext.Posts.Where(m => m.AuthorId == id).ToList();
            var ser = userManager.Users.Where(m => m.Id == posts[0].AuthorId).FirstOrDefault();
            ViewData["UserName"] = ser.UserName;
            return View(posts);
        }

        public ActionResult My1()
        {
            //Post p1 = new Post { BodyText = "Lorem ipsum", AuthorId = User.Identity.GetUserId(), Title = "MyPost", Date = DateTime.Now };
            //postContext.Posts.Add(p1);
            //postContext.SaveChanges();
            string Id = User.Identity.GetUserId();
            Post post = postContext.Posts.Where(m => m.AuthorId == Id).FirstOrDefault();
            List<Comment> list = new List<Comment>();
            var serM = userManager.Users.Where(m => m.Id == Id).FirstOrDefault();

            Comment c1 = new Comment() { AuthorId = "e66c6b02-998a-474f-9e20-ab657e0efb76", BodyText = "Nice post nice post my friend!", PostId = 12, Title = "Good", Author = "vzdendyak", Date = DateTime.Now,post=post};
            Comment c2 = new Comment() { AuthorId = "e66c6b02-998a-474f-9e20-ab657e0efb76", BodyText = "You can better!", PostId = 12, Title = "Now better", Author = "vzdendyak", Date = DateTime.Now, post=post};
            list.Add(c1); list.Add(c2);

            post.Comments = list;
           

            postContext.Entry(post).State = EntityState.Modified;
            postContext.SaveChanges();


            return RedirectToAction("My");
        }


        // GET: Post/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var post = postContext.Posts.Where(m => m.Id == id).FirstOrDefault();
            var coments = postContext.Comments.Where(m => m.PostId == post.Id).ToList();
            ViewData["com"] = coments;
            ViewBag.i = 0;
            ViewBag.coments = coments;
            ViewData["postsId"] = post.Id;
            return View(post);
        }   

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Post/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
          
            var post = postContext.Posts.Where(m => m.Id == id).FirstOrDefault();
            if (post.AuthorId==User.Identity.GetUserId())
            {
                var coments = postContext.Comments.Where(m => m.PostId == post.Id).ToList();
                ViewData["com"] = coments;
                ViewBag.coments = coments;
                return View(post);
            }
            else if (User.IsInRole("admin"))
            {
                var coments = postContext.Comments.Where(m => m.PostId == post.Id).ToList();
                ViewData["com"] = coments;
                ViewBag.coments = coments;
                return View(post);
            }
            return RedirectToAction("My");
           
        }

        // POST: Post/Edit/5
        [HttpPost]
        [Authorize]

        public ActionResult Edit(string text,string title,int postId, FormCollection collection)
        {
            var post = postContext.Posts.Where(m => m.Id == postId).FirstOrDefault();
            post.BodyText = text;
            post.Title = title;

            postContext.SaveChanges();
            dbContext.SaveChanges();
                return RedirectToAction("Index","Home");
           
        }

        // GET: Post/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Post/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult showComment(string postId)
        {
            int NpostId = int.Parse(postId);
            var comments = postContext.Comments.Where(m => m.PostId == NpostId).ToList();
            return PartialView("Comments", comments);
        }
        public ActionResult CommentAdd(string Title,string BodyText, int postId1)
        {
            ViewBag.i=1;

            var post = postContext.Posts.Where(m => m.Id == postId1).FirstOrDefault();
            var coments = postContext.Comments.Where(m => m.PostId == post.Id).ToList();
            string Id = User.Identity.GetUserId();
            //  var posts = postContext.Posts.Where(m => m.AuthorId == Id).ToList();
            
                var ser = userManager.Users.Where(m => m.Id == Id).FirstOrDefault();
                Comment comentTemp = new Comment
                {
                    BodyText = BodyText,
                    Title = "",
                    Author = ser.UserName,
                    AuthorId = ser.Id,
                    Date = DateTime.Now,
                    PostId = postId1,
                    post = post
                };
                postContext.Comments.Add(comentTemp); postContext.SaveChanges(); return PartialView("NewComment", comentTemp);


            return HttpNotFound();
            //ViewData["com"] = coments;
        }
        public ActionResult CommentDelete(int Id)
        {
            var coment = postContext.Comments.Where(m => m.Id == Id).FirstOrDefault();
            var postId = coment.PostId;
            postContext.Comments.Remove(coment);
            postContext.SaveChanges();
            //  return RedirectToAction 

            return RedirectToAction("Details",new { id=postId});
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Details.cshtml
@model Site_Lab12.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}


    <div class="intro">
        <h2>@Model.UserName</h2>
        <div class="hr2"></div>

        <dl class="dl-horizontal">
            <p><b>Нікнейм:</b> @Model.UserName</p>


            @if (User.IsInRole("admin"))
            {
                <p><b>Електронна пошта:</b> @Model.Email</p>

                <p><b>Номер телефону:</b> @Model.PhoneNumber</p>
                @Html.ActionLink("Змінити", "Edit2Async", new { id = Model.Id })

            }
            </p>

            @Html.ActionLink("На головну", "Index")
            <nobr>|</nobr>
            @Html.ActionLink("Написати повідомлення", "Dialog", "Dialog", new { userId = Model.Id }, null)




        </dl>
    </div>
@*<div>
    <hr />
    <dl class="dl-horizontal">
        @if (User.IsInRole("admin"))
        {
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>

        }


        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "UsersList")
</p>*@
<h2>Дописи</h2>

@Html.Partial("PartialUserPosts", ViewData["Posts"])

Views/Home/Edit.cshtml
@model Site_Lab12.Models.ApplicationUser

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.UserName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        

        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("На головну", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Home/Edit2Async.cshtml
@model Site_Lab12.Models.ApplicationUser

@{
    ViewBag.Title = "Edit";
}

<h2>Редагування</h2>

    @using (Html.BeginForm("Edit2Async","Home",FormMethod.Post,new { @class="forms" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <fieldset>
                <ol>
                    <li class="form-row text-input-row">
                        <label>UserName</label>
                        <input type="text" name="UserName" value="@Model.UserName" class="text-input required" title="" />
                        @*@Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })*@

                    </li>
                    <li class="form-row text-input-row">
                        <label>Email</label>
                        <input type="text" name="email" value="@Model.Email" class="text-input required email" title="" />
                        @*@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })*@

                    </li>
                    <li class="form-row text-area-row">
                        <label>Phone number</label>
                        <input type="text" name="PhoneNumber" id="PhoneNumber" value="@Model.PhoneNumber" class="text-input required" title="" />

                    </li>
                    <li class="form-row hidden-row">
                        <input type="hidden" name="hidden" value="" />
                    </li>
                    <li class="button-row">
                        <input type="submit" value="Submit" name="submit" class="btn-submit" />
                    </li>
                </ol>
                <input type="hidden" name="v_email" id="v-email" value="Enter a valid email" />
            </fieldset>
    }
      <br />

@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@Model.UserName</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>



        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Зберегти" class="btn btn-default" />
            </div>
        </div>
    </div>
}*@

<div>
    @Html.ActionLink("На головну", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Home/HomePage.cshtml
@model Site_Lab12.Models.ApplicationUser

@{
    ViewBag.Title = "HomePage";
}
@{
    Layout = "~/Views/Try/new_layout.cshtml";
}

    <div class="intro">
        <h2>Моя сторінка</h2>
        <div class="hr2"></div>
        <h2>@Model.UserName</h2>
        <dl class="dl-horizontal">
            <p><b>Моя пошта:</b> @Model.Email</p>
            <p><b>Мій нікнейм:</b> @Model.UserName</p>
            <p><b>Мій номер телефону:</b> @Model.PhoneNumber</p>
            @foreach (var s in Model.Roles)
            {
                <p>
                    @if (s.RoleId == "fec52346-e68c-41a2-b878-2a5bf51ad1a9")
                    { 

                    <p style="color: red">Ви адмін.</p>
                }
                    </p>
                }
            
            @Html.ActionLink("Змінити", "Edit2Async", new { id = Model.Id }) |
            @Html.ActionLink("На головну", "Index")


        </dl>
    </div>
<p>
   
</p>

Views/Home/LatestPosts.cshtml
@model IEnumerable<Site_Lab12.Models.Post>

@foreach (var i in Model)
{
    <li><span class="date">@Html.ActionLink(i.Title,"Details","Post", new { id=i.Id }, new { @id= "postInfoLink", @style="color: khaki"})
    @*<a href="" id="postInfoLink" style="color: khaki" >@i.Title</a>*@<em class="month"></em></span> <p>@i.BodyText.Substring(0,100)</p></li>
    <hr />
}
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BodyText)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BodyText)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>*@

Views/Home/PartialUserPosts.cshtml
@model IEnumerable<Site_Lab12.Models.Post>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BodyText)
        </th>


        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BodyText)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.ActionLink("Детальніше", "Details", "Post", new { id = item.Id }, null)
                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Змінити", "Edit", "Post", new { id = item.Id }, null) <br />
                    @Html.ActionLink("Видалити", "Details", "Post", new { id = item.Id }, null)

                }
            </td>
        </tr>
    }

</table>

Views/Home/UsersList.cshtml
@model IEnumerable<Site_Lab12.Models.ApplicationUser>
@{
    ViewBag.Title = "Користувачі Speach";
}
@using Microsoft.AspNet.Identity

<h2>Користувачі <i>Speach</i></h2>

<div class="main">

    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            @if (User.IsInRole("admin"))
            {

           
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th> }

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            if (User.Identity.GetUserId()==item.Id)
            {
                continue;
            }
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        @if (User.IsInRole("admin"))
        {
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>}
            <td>

                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @*<input id="btnLogin" type="button" value="Send Message" />*@
                @Html.ActionLink("Send message", "Dialog", "Dialog", new { userId = item.Id }, null) <nobr>|</nobr>


                @if (User.IsInRole("admin"))
                {
                    @Html.ActionLink("Edit", "Edit2Async", new { id = item.Id }) <nobr>|</nobr>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                }
            </td>
        </tr>
        }

    </table>
    <div id="loginBlock">
        @*@Html.Hidden("txtUserName",User.Identity.Name)*@
        <input id="txtUserName" type="text" value="@User.Identity.Name" hidden="hidden" />
        @*<input id="btnLogin" type="button" value="Войти" />*@
    </div>
    <div id="chatBody">
        <div id="header"></div>
        <div id="inputForm">
            <input type="text" id="message" />
            <input type="button" id="sendmessage" value="Отправить" />
        </div>
        <div id="chatroom"></div>

        <div id="chatusers">
            <p><b>Все пользователи</b></p>
        </div>
    </div>
    <input id="hdId" type="hidden" />
    <input id="username" type="hidden" />
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<!--Ссылка на библиотеку SignalR -->
<script src="~/Scripts/jquery.signalR-2.2.2.min.js"></script>
<!--Ссылка на автоматически сгенерированный скрипт хаба SignalR -->
<script src="~/signalr/hubs"></script>
<script src="~/Scripts/util.js"></script>